
logging:
  pattern:
    level: DEBUG

server:
  port: 9081
  servletPath: /*

management:
  security:
   enabled: false

spring:
  application:
    name: springboot-streaming
  cloud:
     instance-count: 1
     instance-index: 0
     stream:
        kafka:
          binder:
            brokers: localhost:9092
            zk-nodes: localhost:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
        bindings:
          output:
            destination: event-demo
            content-type: text/plain
            producer:
              partitionCount: 1
